# Generated by Django 5.2.4 on 2025-07-08 11:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('categorie', models.CharField(choices=[('ELECTRONIQUE', 'Électronique'), ('HABILLEMENT', 'Habillement'), ('LIVRES', 'Livres & Médias'), ('MAISON', 'Maison & Jardin'), ('SPORT', 'Sport & Loisirs'), ('VEHICULES', 'Véhicules'), ('SERVICES', 'Services'), ('AUTRES', 'Autres')], default='AUTRES', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='annonces_photos/')),
                ('valeur_estimee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('OUVERT', 'Ouvert'), ('ECHANGE', 'Échangé'), ('FERME', 'Fermé')], default='OUVERT', max_length=10)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
