# Generated by Django 5.2.4 on 2025-07-08 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('troquetout_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Catégories',
            },
        ),
        migrations.RenameField(
            model_name='annonce',
            old_name='utilisateur',
            new_name='auteur',
        ),
        migrations.RenameField(
            model_name='annonce',
            old_name='date_creation',
            new_name='date_publication',
        ),
        migrations.RemoveField(
            model_name='annonce',
            name='statut',
        ),
        migrations.AlterField(
            model_name='annonce',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='annonces/'),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='troquetout_app.categorie'),
        ),
    ]
