# Generated by Django 5.2.4 on 2025-07-09 11:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('troquetout_app', '0002_categorie_rename_utilisateur_annonce_auteur_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='annonce',
            options={'ordering': ['-date_publication']},
        ),
        migrations.AddField(
            model_name='annonce',
            name='localisation',
            field=models.CharField(blank=True, help_text="Ville, code postal ou région de l'objet.", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='annonce',
            name='statut',
            field=models.CharField(choices=[('OUVERT', 'Ouvert'), ('ECHANGE', 'Échangé'), ('FERME', 'Fermé')], default='OUVERT', max_length=10),
        ),
        migrations.AddField(
            model_name='annonce',
            name='type_annonce',
            field=models.CharField(choices=[('echange', 'Échange'), ('vente', 'Vente')], default='echange', help_text="Indique si c'est une offre d'échange ou de vente.", max_length=10),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='annonces_photos/'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
