# Generated by Django 5.2.4 on 2025-07-09 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('troquetout_app', '0003_alter_annonce_options_annonce_localisation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='adresse',
            field=models.CharField(blank=True, help_text="L'adresse précise pour l'échange (optionnel).", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='annonce',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='Adresse email de contact différente de votre compte (optionnel).', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='annonce',
            name='contact_telephone',
            field=models.CharField(blank=True, help_text='Numéro de téléphone pour les contacts (optionnel).', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='auteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annonces', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annonces_par_categorie', to='troquetout_app.categorie'),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='type_annonce',
            field=models.CharField(choices=[('echange', 'Échange'), ('vente', 'Vente'), ('don', 'Don'), ('offrir', 'Offrir')], default='echange', help_text="Indique si c'est une offre d'échange, de vente, de don ou une proposition.", max_length=10),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='valeur_estimee',
            field=models.CharField(blank=True, help_text="Ex: 50€ ou 'Négociable'", max_length=100, null=True),
        ),
    ]
