# Generated by Django 5.2.4 on 2025-07-10 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('troquetout_app', '0005_contactmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ['-date_soumission'], 'verbose_name': 'Message de Contact', 'verbose_name_plural': 'Messages de Contact'},
        ),
    ]
