# Generated by Django 5.2.4 on 2025-07-10 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('troquetout_app', '0006_alter_contactmessage_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Abonné Newsletter',
                'verbose_name_plural': 'Abonnés Newsletter',
                'ordering': ['-subscribed_at'],
            },
        ),
    ]
