# Generated by Django 5.2.4 on 2025-07-11 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('troquetout_app', '0008_commentaire_annoncelikedislike'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropositionTroc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True)),
                ('date_proposition', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('acceptee', 'Acceptée'), ('refusee', 'Refusée'), ('annulee', 'Annulée')], default='en_attente', max_length=20)),
                ('annonce_cible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propositions_recues_par_cet_article_cible', to='troquetout_app.annonce')),
                ('annonce_proposee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propositions_recues_pour_cet_article', to='troquetout_app.annonce')),
                ('propose_par', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propositions_faites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Propositions de Troc',
                'ordering': ['-date_proposition'],
            },
        ),
    ]
