# Generated by Django 5.2.4 on 2025-07-11 13:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('troquetout_app', '0010_alter_propositiontroc_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='Proposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Message de la proposition')),
                ('date_proposition', models.DateTimeField(auto_now_add=True, verbose_name='Date de la proposition')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('acceptee', 'Acceptée'), ('refusee', 'Refusée'), ('annulee', 'Annulée')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('annonce_cible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propositions_recues_par_cet_article_cible', to='troquetout_app.annonce', verbose_name='Annonce ciblée')),
                ('annonce_proposee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propositions_recues_pour_cet_article', to='troquetout_app.annonce', verbose_name='Annonce proposée')),
                ('propose_par', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propositions_faites', to=settings.AUTH_USER_MODEL, verbose_name='Proposée par')),
            ],
            options={
                'verbose_name': 'Proposition de troc',
                'verbose_name_plural': 'Propositions de Troc',
                'ordering': ['-date_proposition'],
                'unique_together': {('annonce_cible', 'annonce_proposee', 'propose_par')},
            },
        ),
        migrations.DeleteModel(
            name='PropositionTroc',
        ),
    ]
